# Note: Uncomment to start CD
name: CD
on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering on GitHub UI
jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo rsync -avz --delete ./ /home/ubuntu
