# Note: Uncomment to start CD
name: CD
on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering on GitHub UI
jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ ! -d "/home/ubuntu/etl-coincap" ]; then
              git clone https://github.com/bdbao/etl-coincap /home/ubuntu/etl-coincap
            else
              cd /home/ubuntu/etl-coincap
              git config --global --add safe.directory /home/ubuntu/etl-coincap
              git pull origin main
            fi
