# Note: Uncomment to start CI
name: CI
on: 
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering on GitHub UI
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Spin up containers
        run: make up
      - name: Run CI test
        run: make ci
